### ISSUE TITLE
SLF4J Issue

### ISSUE THREAD

**Issue by PedroBuitrago** [kiegroup/jbpm-work-items#109]
Hi,

I am trying to install jbpm-work-items with with

C:\Verano\dev\gitdownloads\jbpm-work-items>mvn clean install

However I found next error:

[INFO] Running org.jbpm.process.workitem.archive.ArchiveWorkitemIntegrationTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.733 s <<< FAILURE! - in org.jbpm.process.workitem.archive.ArchiveWorkitemIntegrationTest
[ERROR] testWorkitemValidity(org.jbpm.process.workitem.archive.ArchiveWorkitemIntegrationTest)  Time elapsed: 4.591 s  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
        at org.jbpm.process.workitem.archive.ArchiveWorkitemIntegrationTest.testWorkitemValidity(ArchiveWorkitemIntegrationTest.java:38)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ArchiveWorkitemIntegrationTest.testWorkitemValidity:38 expected:<1> but was:<0>
[INFO]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO]

**Comment by PedroBuitrago** [comment]
This is the fail report:

<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-failsafe-plugin/xsd/failsafe-test-report.xsd" name="org.jbpm.process.workitem.archive.ArchiveWorkitemIntegrationTest" time="4.733" tests="1" errors="0" skipped="0" failures="1">
  <properties>
    <property name="sun.desktop" value="windows"/>
    <property name="awt.toolkit" value="sun.awt.windows.WToolkit"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="sun.cpu.isalist" value="amd64"/>
    <property name="groupId" value="org.jbpm.contrib"/>
    <property name="sun.jnu.encoding" value="Cp1252"/>
    <property name="java.class.path" value="C:\Verano\dev\gitdownloads\jbpm-work-items\archive-workitem\target\test-classes;C:\Verano\dev\gitdownloads\jbpm-work-items\archive-workitem\target\archive-workitem-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\apache\commons\commons-compress\1.12\commons-compress-1.12.jar;C:\Users\pbuitrago\.m2\repository\org\kie\kie-api\7.27.0-SNAPSHOT\kie-api-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\kie\soup\kie-soup-maven-support\7.27.0-SNAPSHOT\kie-soup-maven-support-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\jbpm\jbpm-workitems-core\7.27.0-SNAPSHOT\jbpm-workitems-core-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\drools\drools-core\7.27.0-SNAPSHOT\drools-core-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\mvel\mvel2\2.4.4.Final\mvel2-2.4.4.Final.jar;C:\Users\pbuitrago\.m2\repository\org\kie\soup\kie-soup-commons\7.27.0-SNAPSHOT\kie-soup-commons-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\kie\soup\kie-soup-project-datamodel-commons\7.27.0-SNAPSHOT\kie-soup-project-datamodel-commons-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\kie\soup\kie-soup-project-datamodel-api\7.27.0-SNAPSHOT\kie-soup-project-datamodel-api-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\pbuitrago\.m2\repository\org\jbpm\jbpm-flow\7.27.0-SNAPSHOT\jbpm-flow-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\kie\kie-dmn-feel\7.27.0-SNAPSHOT\kie-dmn-feel-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\antlr\antlr4-runtime\4.7.2\antlr4-runtime-4.7.2.jar;C:\Users\pbuitrago\.m2\repository\com\github\javaparser\javaparser-core\3.13.10\javaparser-core-3.13.10.jar;C:\Users\pbuitrago\.m2\repository\org\drools\drools-mvel-parser\7.27.0-SNAPSHOT\drools-mvel-parser-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\jboss\spec\javax\annotation\jboss-annotations-api_1.2_spec\1.0.0.Final\jboss-annotations-api_1.2_spec-1.0.0.Final.jar;C:\Users\pbuitrago\.m2\repository\ch\obermuhlner\big-math\2.0.1\big-math-2.0.1.jar;C:\Users\pbuitrago\.m2\repository\org\kie\kie-dmn-core\7.27.0-SNAPSHOT\kie-dmn-core-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\kie\kie-dmn-backend\7.27.0-SNAPSHOT\kie-dmn-backend-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\drools\drools-canonical-model\7.27.0-SNAPSHOT\drools-canonical-model-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\drools\drools-model-compiler\7.27.0-SNAPSHOT\drools-model-compiler-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\drools\drools-mvel-compiler\7.27.0-SNAPSHOT\drools-mvel-compiler-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\jpmml\pmml-model\1.4.11\pmml-model-1.4.11.jar;C:\Users\pbuitrago\.m2\repository\org\jpmml\pmml-agent\1.4.11\pmml-agent-1.4.11.jar;C:\Users\pbuitrago\.m2\repository\com\google\protobuf\protobuf-java\3.6.1\protobuf-java-3.6.1.jar;C:\Users\pbuitrago\.m2\repository\org\apache\commons\commons-lang3\3.8.1\commons-lang3-3.8.1.jar;C:\Users\pbuitrago\.m2\repository\org\jbpm\jbpm-bpmn2\7.27.0-SNAPSHOT\jbpm-bpmn2-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\drools\drools-compiler\7.27.0-SNAPSHOT\drools-compiler-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\eclipse\jdt\core\compiler\ecj\4.6.1\ecj-4.6.1.jar;C:\Users\pbuitrago\.m2\repository\com\thoughtworks\xstream\xstream\1.4.11.1\xstream-1.4.11.1.jar;C:\Users\pbuitrago\.m2\repository\xmlpull\xmlpull\1.1.3.1\xmlpull-1.1.3.1.jar;C:\Users\pbuitrago\.m2\repository\xpp3\xpp3_min\1.1.4c\xpp3_min-1.1.4c.jar;C:\Users\pbuitrago\.m2\repository\org\jbpm\jbpm-flow-builder\7.27.0-SNAPSHOT\jbpm-flow-builder-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\kie\kie-internal\7.27.0-SNAPSHOT\kie-internal-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\kie\kie-dmn-api\7.27.0-SNAPSHOT\kie-dmn-api-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\kie\kie-dmn-model\7.27.0-SNAPSHOT\kie-dmn-model-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\commons-io\commons-io\2.6\commons-io-2.6.jar;C:\Users\pbuitrago\.m2\repository\org\apache\commons\commons-exec\1.3\commons-exec-1.3.jar;C:\Users\pbuitrago\.m2\repository\org\antlr\ST4\4.0.7\ST4-4.0.7.jar;C:\Users\pbuitrago\.m2\repository\org\antlr\antlr-runtime\3.5.2\antlr-runtime-3.5.2.jar;C:\Users\pbuitrago\.m2\repository\org\jbpm\jbpm-workitems-core\7.27.0-SNAPSHOT\jbpm-workitems-core-7.27.0-SNAPSHOT-tests.jar;C:\Users\pbuitrago\.m2\repository\junit\junit\4.12\junit-4.12.jar;C:\Users\pbuitrago\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\pbuitrago\.m2\repository\org\slf4j\slf4j-api\1.7.26\slf4j-api-1.7.26.jar;C:\Verano\dev\gitdownloads\jbpm-work-items\template-resources\target\template-resources-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\mockito\mockito-core\1.10.19\mockito-core-1.10.19.jar;C:\Users\pbuitrago\.m2\repository\org\objenesis\objenesis\2.1\objenesis-2.1.jar;"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="user.variant" value=""/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="user.timezone" value="America/Bogota"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="os.name" value="Windows 10"/>
    <property name="user.country" value="CO"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.boot.library.path" value="C:\Program Files\Java\jdk1.8.0_211\jre\bin"/>
    <property name="sun.java.command" value="C:\Users\PBUITR~1\AppData\Local\Temp\surefire1551991141882570604\surefirebooter3222824666893396707.jar C:\Users\pbuitrago\AppData\Local\Temp\surefire1551991141882570604 2019-09-11T12-07-09_730-jvmRun1 surefire8132016268708336639tmp surefire_04481783091874015628tmp"/>
    <property name="surefire.test.class.path" value="C:\Verano\dev\gitdownloads\jbpm-work-items\archive-workitem\target\test-classes;C:\Verano\dev\gitdownloads\jbpm-work-items\archive-workitem\target\archive-workitem-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\apache\commons\commons-compress\1.12\commons-compress-1.12.jar;C:\Users\pbuitrago\.m2\repository\org\kie\kie-api\7.27.0-SNAPSHOT\kie-api-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\kie\soup\kie-soup-maven-support\7.27.0-SNAPSHOT\kie-soup-maven-support-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\jbpm\jbpm-workitems-core\7.27.0-SNAPSHOT\jbpm-workitems-core-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\drools\drools-core\7.27.0-SNAPSHOT\drools-core-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\mvel\mvel2\2.4.4.Final\mvel2-2.4.4.Final.jar;C:\Users\pbuitrago\.m2\repository\org\kie\soup\kie-soup-commons\7.27.0-SNAPSHOT\kie-soup-commons-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\kie\soup\kie-soup-project-datamodel-commons\7.27.0-SNAPSHOT\kie-soup-project-datamodel-commons-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\kie\soup\kie-soup-project-datamodel-api\7.27.0-SNAPSHOT\kie-soup-project-datamodel-api-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\pbuitrago\.m2\repository\org\jbpm\jbpm-flow\7.27.0-SNAPSHOT\jbpm-flow-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\kie\kie-dmn-feel\7.27.0-SNAPSHOT\kie-dmn-feel-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\antlr\antlr4-runtime\4.7.2\antlr4-runtime-4.7.2.jar;C:\Users\pbuitrago\.m2\repository\com\github\javaparser\javaparser-core\3.13.10\javaparser-core-3.13.10.jar;C:\Users\pbuitrago\.m2\repository\org\drools\drools-mvel-parser\7.27.0-SNAPSHOT\drools-mvel-parser-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\jboss\spec\javax\annotation\jboss-annotations-api_1.2_spec\1.0.0.Final\jboss-annotations-api_1.2_spec-1.0.0.Final.jar;C:\Users\pbuitrago\.m2\repository\ch\obermuhlner\big-math\2.0.1\big-math-2.0.1.jar;C:\Users\pbuitrago\.m2\repository\org\kie\kie-dmn-core\7.27.0-SNAPSHOT\kie-dmn-core-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\kie\kie-dmn-backend\7.27.0-SNAPSHOT\kie-dmn-backend-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\drools\drools-canonical-model\7.27.0-SNAPSHOT\drools-canonical-model-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\drools\drools-model-compiler\7.27.0-SNAPSHOT\drools-model-compiler-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\drools\drools-mvel-compiler\7.27.0-SNAPSHOT\drools-mvel-compiler-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\jpmml\pmml-model\1.4.11\pmml-model-1.4.11.jar;C:\Users\pbuitrago\.m2\repository\org\jpmml\pmml-agent\1.4.11\pmml-agent-1.4.11.jar;C:\Users\pbuitrago\.m2\repository\com\google\protobuf\protobuf-java\3.6.1\protobuf-java-3.6.1.jar;C:\Users\pbuitrago\.m2\repository\org\apache\commons\commons-lang3\3.8.1\commons-lang3-3.8.1.jar;C:\Users\pbuitrago\.m2\repository\org\jbpm\jbpm-bpmn2\7.27.0-SNAPSHOT\jbpm-bpmn2-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\drools\drools-compiler\7.27.0-SNAPSHOT\drools-compiler-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\eclipse\jdt\core\compiler\ecj\4.6.1\ecj-4.6.1.jar;C:\Users\pbuitrago\.m2\repository\com\thoughtworks\xstream\xstream\1.4.11.1\xstream-1.4.11.1.jar;C:\Users\pbuitrago\.m2\repository\xmlpull\xmlpull\1.1.3.1\xmlpull-1.1.3.1.jar;C:\Users\pbuitrago\.m2\repository\xpp3\xpp3_min\1.1.4c\xpp3_min-1.1.4c.jar;C:\Users\pbuitrago\.m2\repository\org\jbpm\jbpm-flow-builder\7.27.0-SNAPSHOT\jbpm-flow-builder-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\kie\kie-internal\7.27.0-SNAPSHOT\kie-internal-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\kie\kie-dmn-api\7.27.0-SNAPSHOT\kie-dmn-api-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\kie\kie-dmn-model\7.27.0-SNAPSHOT\kie-dmn-model-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\commons-io\commons-io\2.6\commons-io-2.6.jar;C:\Users\pbuitrago\.m2\repository\org\apache\commons\commons-exec\1.3\commons-exec-1.3.jar;C:\Users\pbuitrago\.m2\repository\org\antlr\ST4\4.0.7\ST4-4.0.7.jar;C:\Users\pbuitrago\.m2\repository\org\antlr\antlr-runtime\3.5.2\antlr-runtime-3.5.2.jar;C:\Users\pbuitrago\.m2\repository\org\jbpm\jbpm-workitems-core\7.27.0-SNAPSHOT\jbpm-workitems-core-7.27.0-SNAPSHOT-tests.jar;C:\Users\pbuitrago\.m2\repository\junit\junit\4.12\junit-4.12.jar;C:\Users\pbuitrago\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\pbuitrago\.m2\repository\org\slf4j\slf4j-api\1.7.26\slf4j-api-1.7.26.jar;C:\Verano\dev\gitdownloads\jbpm-work-items\template-resources\target\template-resources-7.27.0-SNAPSHOT.jar;C:\Users\pbuitrago\.m2\repository\org\mockito\mockito-core\1.10.19\mockito-core-1.10.19.jar;C:\Users\pbuitrago\.m2\repository\org\objenesis\objenesis\2.1\objenesis-2.1.jar;"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="user.home" value="C:\Users\pbuitrago"/>
    <property name="user.language" value="es"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="java.home" value="C:\Program Files\Java\jdk1.8.0_211\jre"/>
    <property name="version" value="7.27.0-SNAPSHOT"/>
    <property name="basedir" value="C:\Verano\dev\gitdownloads\jbpm-work-items\archive-workitem"/>
    <property name="file.separator" value="\"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.awt.graphicsenv" value="sun.awt.Win32GraphicsEnvironment"/>
    <property name="surefire.real.class.path" value="C:\Users\PBUITR~1\AppData\Local\Temp\surefire1551991141882570604\surefirebooter3222824666893396707.jar"/>
    <property name="sun.boot.class.path" value="C:\Program Files\Java\jdk1.8.0_211\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\sunrsasign.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_211\jre\classes"/>
    <property name="user.script" value=""/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="java.runtime.version" value="1.8.0_211-b12"/>
    <property name="user.name" value="pbuitrago"/>
    <property name="path.separator" value=";"/>
    <property name="os.version" value="10.0"/>
    <property name="java.endorsed.dirs" value="C:\Program Files\Java\jdk1.8.0_211\jre\lib\endorsed"/>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="artifactId" value="archive-workitem"/>
    <property name="localRepository" value="C:\Users\pbuitrago\.m2\repository"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="java.io.tmpdir" value="C:\Users\PBUITR~1\AppData\Local\Temp\"/>
    <property name="java.version" value="1.8.0_211"/>
    <property name="user.dir" value="C:\Verano\dev\gitdownloads\jbpm-work-items\archive-workitem"/>
    <property name="builddir" value="C:\Verano\dev\gitdownloads\jbpm-work-items\archive-workitem\target"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="java.awt.printerjob" value="sun.awt.windows.WPrinterJob"/>
    <property name="sun.os.patch.level" value=""/>
    <property name="java.library.path" value="C:\Program Files\Java\jdk1.8.0_211\jre\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Java\jdk1.8.0_211\bin;C:\Verano\dev\apache-maven-3.6.1\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Git\cmd;C:\Users\pbuitrago\AppData\Local\Microsoft\WindowsApps;;."/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="java.vm.version" value="25.211-b12"/>
    <property name="java.ext.dirs" value="C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext;C:\WINDOWS\Sun\Java\lib\ext"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="java.class.version" value="52.0"/>
  </properties>
  <testcase name="testWorkitemValidity" classname="org.jbpm.process.workitem.archive.ArchiveWorkitemIntegrationTest" time="4.591">
    <failure message="expected:&lt;1&gt; but was:&lt;0&gt;" type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError: expected:<1> but was:<0>
	at org.jbpm.process.workitem.archive.ArchiveWorkitemIntegrationTest.testWorkitemValidity(ArchiveWorkitemIntegrationTest.java:38)
]]></failure>
    <system-err><![CDATA[SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
]]></system-err>
  </testcase>
</testsuite>

**Comment by PedroBuitrago** [comment]
If I tried to run repository-springboot ( mvn clean install ) or, even, java -jar repository-springboot-7.27.0-SNAPSHOT.jar but I got: 

<html><script id="tinyhippos-injected">if (window.top.ripple) { window.top.ripple("bootstrap").inject(window, document); }</script><head></head><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id="created">Wed Sep 11 15:12:27 COT 2019</div><div>There was an unexpected error (type=Not Found, status=404).</div><div>No message available</div></body></html>

**Comment by tsurdilo** [comment]
Hi @PedroBuitrago, I am unable to reproduce the issues with build and starting the repository-springboot module. Could you let us know what java version you are running and the OS?

**Comment by PedroBuitrago** [comment]
Hi, 
JVM: java version "1.8.0_211"
OS: Windows 10 Pro x64

Does your build run if you skip integration tests? Yes, If I skip integration test.. I could deploy the application.
